### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Forlogen** [steph1793/Pointer_Generator_Summarizer#1]
Hi,Could you tell me your commands for training the model?and I use finiseh_files/train.bin to train the model,but not reaction, it just build the vocabulary...Thank you

**Comment by steph1793** [comment]
hi, @Forlogen
Sorry for responding so late.
In fact, the current version is the 3rd one I released. it uses tensorflow 2.0.0 and in order to make the most out of this version, i choose to build a data pipeline using tf dataset (reading tfrecords files instead of bins). In this [repo](https://github.com/steph1793/CNN-DailyMail-Bin-To-TFRecords), you can transform your bin files into tfrecords files.
finally,  below you can find a command line to launch your program. Fell free to tune the hyperparameters, I choose to reproduce those in the paper.


!python main.py \
--max_enc_len=400 \
--max_dec_len=100 \
--max_dec_steps=120 \
--min_dec_steps=30 \
--batch_size=16 \
--beam_size=4 \
--vocab_size=50000 \
--embed_size=128 \
--enc_units=256 \
--dec_units=256 \
--attn_units=512 \
--learning_rate=0.15 \
--adagrad_init_acc=0.1 \
--max_grad_norm=0.8 \
--mode="train" \
--checkpoints_save_steps=5000 \
--max_steps=38000 \
--num_to_test=20 \
--max_num_to_eval=100 \
--vocab_path="<vocab_path>" \
--data_dir="<data_dir>" \
--model_path="" \
--checkpoint_dir="<checkpoint_to_save_dir>" \
--test_save_dir=""
